### ISSUE TITLE
GAE：louvain, wcc, lpa not support graph whose oid_type is 'string' 

### ISSUE THREAD

**Issue by dzhiwei** [alibaba/GraphScope#2084] opened 2022-09-27 03:18 UTC
**Describe the bug**
louvain, wcc, lpa are working fine with graphs with oid_type=='int64', but error will happen after I set iod_type == 'string'  when load graph.

**To Reproduce**
```shell
import graphscope
from graphscope.dataset import load_p2p_network
from graphscope.client.session import get_default_session
import os

graphscope.set_option(show_log=True)
graphscope.set_option(log_level="DEBUG")
prefix = os.getcwd() + "/data"

def execute():
    sess = graphscope.session(cluster_type="hosts", mode="eager")

    g = sess.g(directed=False, oid_type="string")
    g = g.add_vertices(
        os.path.join(prefix, "p2p-31_property_v_0"), "host"
    ).add_edges(
        os.path.join(prefix, "p2p-31_property_e_0"),
        "connect",
        src_label="host",
        dst_label="host",
    )
    # project to a simple graph (if needed)
    pg = g.project(vertices={"host": ["id"]}, edges={"connect": ["dist"]})
    c = graphscope.louvain(pg, min_progress=1000, progress_tries=1)
    # c = graphscope.wcc(pg)
    # c = graphscope.lpa(pg)

    dataframe = c.to_dataframe(selector={'id': 'v.id', 'result': 'r'})
    print(dataframe)

    sess.close()


if __name__ == "__main__":
    execute()
```

log: 

```
I20220927 11:15:22.000000 85512192 /Users/runner/work/GraphScope/GraphScope/analytical_engine/core/grape_instance.cc:1178] Registering Graph, graph type: ARROW_PROJECTED, Type sigature: e1ba0796515bc85372f70618d0a21153e68a0e3f26e9374eebe573551acb16b9, lib path: /tmp/gs/builtin/e1ba0796515bc85372f70618d0a21153e68a0e3f26e9374eebe573551acb16b9/libe1ba0796515bc85372f70618d0a21153e68a0e3f26e9374eebe573551acb16b9.dylib
I20220927 11:15:22.000000 141914112 /Users/runner/work/GraphScope/GraphScope/analytical_engine/core/grape_instance.cc:1178] Registering Graph, graph type: ARROW_PROJECTED, Type sigature: e1ba0796515bc85372f70618d0a21153e68a0e3f26e9374eebe573551acb16b9, lib path: /tmp/gs/builtin/e1ba0796515bc85372f70618d0a21153e68a0e3f26e9374eebe573551acb16b9/libe1ba0796515bc85372f70618d0a21153e68a0e3f26e9374eebe573551acb16b9.dylib
I20220927 11:15:22.000000 85512192 /Users/runner/work/GraphScope/GraphScope/analytical_engine/core/object/gs_object.h:66] Object e1ba0796515bc85372f70618d0a21153e68a0e3f26e9374eebe573551acb16b9[ProjectUtils] is destructed.
I20220927 11:15:22.000000 141914112 /Users/runner/work/GraphScope/GraphScope/analytical_engine/core/object/gs_object.h:66] Object e1ba0796515bc85372f70618d0a21153e68a0e3f26e9374eebe573551acb16b9[ProjectUtils] is destructed.
2022-09-27 11:15:22,099 [ERROR][coordinator:432]: Engine RunStep failed, code: INTERNAL, details: /Users/runner/work/GraphScope/GraphScope/analytical_engine/core/utils/lib_utils.h:38: open_lib -> Failed to open library: /tmp/gs/builtin/e1ba0796515bc85372f70618d0a21153e68a0e3f26e9374eebe573551acb16b9/libe1ba0796515bc85372f70618d0a21153e68a0e3f26e9374eebe573551acb16b9.dylib. Reason: dlopen(/tmp/gs/builtin/e1ba0796515bc85372f70618d0a21153e68a0e3f26e9374eebe573551acb16b9/libe1ba0796515bc85372f70618d0a21153e68a0e3f26e9374eebe573551acb16b9.dylib, 0x0001): symbol not found in flat namespace '__ZN8vineyard10ObjectMeta11AddKeyValueERKNSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEERKN8nlohmann12json_v3_11_110basic_jsonINS1_3mapENS1_6vectorES7_bxydS5_NSB_14adl_serializerENSE_IhNS5_IhEEEEEE'
/Users/runner/work/GraphScope/GraphScope/analytical_engine/core/utils/lib_utils.h:38: open_lib -> Failed to open library: /tmp/gs/builtin/e1ba0796515bc85372f70618d0a21153e68a0e3f26e9374eebe573551acb16b9/libe1ba0796515bc85372f70618d0a21153e68a0e3f26e9374eebe573551acb16b9.dylib. Reason: dlopen(/tmp/gs/builtin/e1ba0796515bc85372f70618d0a21153e68a0e3f26e9374eebe573551acb16b9/libe1ba0796515bc85372f70618d0a21153e68a0e3f26e9374eebe573551acb16b9.dylib, 0x0001): symbol not found in flat namespace '__ZN8vineyard10ObjectMeta11AddKeyValueERKNSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEERKN8nlohmann12json_v3_11_110basic_jsonINS1_3mapENS1_6vectorES7_bxydS5_NSB_14adl_serializerENSE_IhNS5_IhEEEEEE'

2022-09-27 11:15:22,102 [ERROR][rpc:187]: Runstep failed with code: ANALYTICAL_ENGINE_INTERNAL_ERROR, message: Error occurred during preprocessing, The traceback is: Traceback (most recent call last):
  File "/Users/du/.conda/envs/GraphAnalysticEngine/lib/python3.8/site-packages/gscoordinator/coordinator.py", line 426, in run_on_analytical_engine
    for response in responses:
  File "/Users/du/.conda/envs/GraphAnalysticEngine/lib/python3.8/site-packages/grpc/_channel.py", line 426, in __next__
    return self._next()
  File "/Users/du/.conda/envs/GraphAnalysticEngine/lib/python3.8/site-packages/grpc/_channel.py", line 826, in _next
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.INTERNAL
	details = "/Users/runner/work/GraphScope/GraphScope/analytical_engine/core/utils/lib_utils.h:38: open_lib -> Failed to open library: /tmp/gs/builtin/e1ba0796515bc85372f70618d0a21153e68a0e3f26e9374eebe573551acb16b9/libe1ba0796515bc85372f70618d0a21153e68a0e3f26e9374eebe573551acb16b9.dylib. Reason: dlopen(/tmp/gs/builtin/e1ba0796515bc85372f70618d0a21153e68a0e3f26e9374eebe573551acb16b9/libe1ba0796515bc85372f70618d0a21153e68a0e3f26e9374eebe573551acb16b9.dylib, 0x0001): symbol not found in flat namespace '__ZN8vineyard10ObjectMeta11AddKeyValueERKNSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEERKN8nlohmann12json_v3_11_110basic_jsonINS1_3mapENS1_6vectorES7_bxydS5_NSB_14adl_serializerENSE_IhNS5_IhEEEEEE'
/Users/runner/work/GraphScope/GraphScope/analytical_engine/core/utils/lib_utils.h:38: open_lib -> Failed to open library: /tmp/gs/builtin/e1ba0796515bc85372f70618d0a21153e68a0e3f26e9374eebe573551acb16b9/libe1ba0796515bc85372f70618d0a21153e68a0e3f26e9374eebe573551acb16b9.dylib. Reason: dlopen(/tmp/gs/builtin/e1ba0796515bc85372f70618d0a21153e68a0e3f26e9374eebe573551acb16b9/libe1ba0796515bc85372f70618d0a21153e68a0e3f26e9374eebe573551acb16b9.dylib, 0x0001): symbol not found in flat namespace '__ZN8vineyard10ObjectMeta11AddKeyValueERKNSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEERKN8nlohmann12json_v3_11_110basic_jsonINS1_3mapENS1_6vectorES7_bxydS5_NSB_14adl_serializerENSE_IhNS5_IhEEEEEE'
"
	debug_error_string = "{"created":"@1664248522.099392000","description":"Error received from peer ipv6:[::1]:62503","file":"src/core/lib/surface/call.cc","file_line":967,"grpc_message":"/Users/runner/work/GraphScope/GraphScope/analytical_engine/core/utils/lib_utils.h:38: open_lib -> Failed to open library: /tmp/gs/builtin/e1ba0796515bc85372f70618d0a21153e68a0e3f26e9374eebe573551acb16b9/libe1ba0796515bc85372f70618d0a21153e68a0e3f26e9374eebe573551acb16b9.dylib. Reason: dlopen(/tmp/gs/builtin/e1ba0796515bc85372f70618d0a21153e68a0e3f26e9374eebe573551acb16b9/libe1ba0796515bc85372f70618d0a21153e68a0e3f26e9374eebe573551acb16b9.dylib, 0x0001): symbol not found in flat namespace '__ZN8vineyard10ObjectMeta11AddKeyValueERKNSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEERKN8nlohmann12json_v3_11_110basic_jsonINS1_3mapENS1_6vectorES7_bxydS5_NSB_14adl_serializerENSE_IhNS5_IhEEEEEE'\n/Users/runner/work/GraphScope/GraphScope/analytical_engine/core/utils/lib_utils.h:38: open_lib -> Failed to open library: /tmp/gs/builtin/e1ba0796515bc85372f70618d0a21153e68a0e3f26e9374eebe573551acb16b9/libe1ba0796515bc85372f70618d0a21153e68a0e3f26e9374eebe573551acb16b9.dylib. Reason: dlopen(/tmp/gs/builtin/e1ba0796515bc85372f70618d0a21153e68a0e3f26e9374eebe573551acb16b9/libe1ba0796515bc85372f70618d0a21153e68a0e3f26e9374eebe573551acb16b9.dylib, 0x0001): symbol not found in flat namespace '__ZN8vineyard10ObjectMeta11AddKeyValueERKNSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEERKN8nlohmann12json_v3_11_110basic_jsonINS1_3mapENS1_6vectorES7_bxydS5_NSB_14adl_serializerENSE_IhNS5_IhEEEEEE'\n","grpc_status":13}"
>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/du/.conda/envs/GraphAnalysticEngine/lib/python3.8/site-packages/gscoordinator/coordinator.py", line 623, in _RunStep
    head, bodies = self.run_on_analytical_engine(
  File "/Users/du/.conda/envs/GraphAnalysticEngine/lib/python3.8/site-packages/gscoordinator/coordinator.py", line 418, in run_on_analytical_engine
    op = self._maybe_register_graph(op, self._session_id)
  File "/Users/du/.conda/envs/GraphAnalysticEngine/lib/python3.8/site-packages/gscoordinator/coordinator.py", line 728, in _maybe_register_graph
    response_head, _ = self.run_on_analytical_engine(dag_def, [], {})
  File "/Users/du/.conda/envs/GraphAnalysticEngine/lib/python3.8/site-packages/gscoordinator/coordinator.py", line 444, in run_on_analytical_engine
    raise AnalyticalEngineInternalError(msg)
graphscope.framework.errors.AnalyticalEngineInternalError: /Users/runner/work/GraphScope/GraphScope/analytical_engine/core/utils/lib_utils.h:38: open_lib -> Failed to open library: /tmp/gs/builtin/e1ba0796515bc85372f70618d0a21153e68a0e3f26e9374eebe573551acb16b9/libe1ba0796515bc85372f70618d0a21153e68a0e3f26e9374eebe573551acb16b9.dylib. Reason: dlopen(/tmp/gs/builtin/e1ba0796515bc85372f70618d0a21153e68a0e3f26e9374eebe573551acb16b9/libe1ba0796515bc85372f70618d0a21153e68a0e3f26e9374eebe573551acb16b9.dylib, 0x0001): symbol not found in flat namespace '__ZN8vineyard10ObjectMeta11AddKeyValueERKNSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEERKN8nlohmann12json_v3_11_110basic_jsonINS1_3mapENS1_6vectorES7_bxydS5_NSB_14adl_serializerENSE_IhNS5_IhEEEEEE'
/Users/runner/work/GraphScope/GraphScope/analytical_engine/core/utils/lib_utils.h:38: open_lib -> Failed to open library: /tmp/gs/builtin/e1ba0796515bc85372f70618d0a21153e68a0e3f26e9374eebe573551acb16b9/libe1ba0796515bc85372f70618d0a21153e68a0e3f26e9374eebe573551acb16b9.dylib. Reason: dlopen(/tmp/gs/builtin/e1ba0796515bc85372f70618d0a21153e68a0e3f26e9374eebe573551acb16b9/libe1ba0796515bc85372f70618d0a21153e68a0e3f26e9374eebe573551acb16b9.dylib, 0x0001): symbol not found in flat namespace '__ZN8vineyard10ObjectMeta11AddKeyValueERKNSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEERKN8nlohmann12json_v3_11_110basic_jsonINS1_3mapENS1_6vectorES7_bxydS5_NSB_14adl_serializerENSE_IhNS5_IhEEEEEE'


E20220927 11:15:22.000000 141914112 /Users/runner/work/GraphScope/GraphScope/analytical_engine/core/server/dispatcher.cc:119] Worker 0: /Users/runner/work/GraphScope/GraphScope/analytical_engine/core/utils/lib_utils.h:38: open_lib -> Failed to open library: /tmp/gs/builtin/e1ba0796515bc85372f70618d0a21153e68a0e3f26e9374eebe573551acb16b9/libe1ba0796515bc85372f70618d0a21153e68a0e3f26e9374eebe573551acb16b9.dylib. Reason: dlopen(/tmp/gs/builtin/e1ba0796515bc85372f70618d0a21153e68a0e3f26e9374eebe573551acb16b9/libe1ba0796515bc85372f70618d0a21153e68a0e3f26e9374eebe573551acb16b9.dylib, 0x0001): symbol not found in flat namespace '__ZN8vineyard10ObjectMeta11AddKeyValueERKNSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEERKN8nlohmann12json_v3_11_110basic_jsonINS1_3mapENS1_6vectorES7_bxydS5_NSB_14adl_serializerENSE_IhNS5_IhEEEEEE'
E20220927 11:15:22.000000 85512192 /Users/runner/work/GraphScope/GraphScope/analytical_engine/core/server/dispatcher.cc:119] Worker 1: /Users/runner/work/GraphScope/GraphScope/analytical_engine/core/utils/lib_utils.h:38: open_lib -> Failed to open library: /tmp/gs/builtin/e1ba0796515bc85372f70618d0a21153e68a0e3f26e9374eebe573551acb16b9/libe1ba0796515bc85372f70618d0a21153e68a0e3f26e9374eebe573551acb16b9.dylib. Reason: dlopen(/tmp/gs/builtin/e1ba0796515bc85372f70618d0a21153e68a0e3f26e9374eebe573551acb16b9/libe1ba0796515bc85372f70618d0a21153e68a0e3f26e9374eebe573551acb16b9.dylib, 0x0001): symbol not found in flat namespace '__ZN8vineyard10ObjectMeta11AddKeyValueERKNSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEERKN8nlohmann12json_v3_11_110basic_jsonINS1_3mapENS1_6vectorES7_bxydS5_NSB_14adl_serializerENSE_IhNS5_IhEEEEEE'
2022-09-27 11:15:22,099 [ERROR][coordinator:432]: Engine RunStep failed, code: INTERNAL, details: /Users/runner/work/GraphScope/GraphScope/analytical_engine/core/utils/lib_utils.h:38: open_lib -> Failed to open library: /tmp/gs/builtin/e1ba0796515bc85372f70618d0a21153e68a0e3f26e9374eebe573551acb16b9/libe1ba0796515bc85372f70618d0a21153e68a0e3f26e9374eebe573551acb16b9.dylib. Reason: dlopen(/tmp/gs/builtin/e1ba0796515bc85372f70618d0a21153e68a0e3f26e9374eebe573551acb16b9/libe1ba0796515bc85372f70618d0a21153e68a0e3f26e9374eebe573551acb16b9.dylib, 0x0001): symbol not found in flat namespace '__ZN8vineyard10ObjectMeta11AddKeyValueERKNSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEERKN8nlohmann12json_v3_11_110basic_jsonINS1_3mapENS1_6vectorES7_bxydS5_NSB_14adl_serializerENSE_IhNS5_IhEEEEEE'
/Users/runner/work/GraphScope/GraphScope/analytical_engine/core/utils/lib_utils.h:38: open_lib -> Failed to open library: /tmp/gs/builtin/e1ba0796515bc85372f70618d0a21153e68a0e3f26e9374eebe573551acb16b9/libe1ba0796515bc85372f70618d0a21153e68a0e3f26e9374eebe573551acb16b9.dylib. Reason: dlopen(/tmp/gs/builtin/e1ba0796515bc85372f70618d0a21153e68a0e3f26e9374eebe573551acb16b9/libe1ba0796515bc85372f70618d0a21153e68a0e3f26e9374eebe573551acb16b9.dylib, 0x0001): symbol not found in flat namespace '__ZN8vineyard10ObjectMeta11AddKeyValueERKNSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEERKN8nlohmann12json_v3_11_110basic_jsonINS1_3mapENS1_6vectorES7_bxydS5_NSB_14adl_serializerENSE_IhNS5_IhEEEEEE'

Traceback (most recent call last):
  File "/Users/du/PycharmProjects/GraphAnalysticEngine/tests/louvain_test.py", line 35, in <module>
    execute()
  File "/Users/du/PycharmProjects/GraphAnalysticEngine/tests/louvain_test.py", line 24, in execute
    c = graphscope.louvain(pg, min_progress=1000, progress_tries=1)
  File "/Users/du/.conda/envs/GraphAnalysticEngine/lib/python3.8/site-packages/graphscope/framework/app.py", line 72, in wrapper
    projected = graph._project_to_simple()
  File "/Users/du/.conda/envs/GraphAnalysticEngine/lib/python3.8/site-packages/graphscope/framework/graph.py", line 899, in _project_to_simple
    return self._session._wrapper(
  File "/Users/du/.conda/envs/GraphAnalysticEngine/lib/python3.8/site-packages/graphscope/client/session.py", line 949, in _wrapper
    return self.run(dag_node)
  File "/Users/du/.conda/envs/GraphAnalysticEngine/lib/python3.8/site-packages/graphscope/client/session.py", line 971, in run
    return self.run_fetches(fetches, debug)
  File "/Users/du/.conda/envs/GraphAnalysticEngine/lib/python3.8/site-packages/graphscope/client/session.py", line 981, in run_fetches
    response = self._grpc_client.run(fetch_handler.targets)
  File "/Users/du/.conda/envs/GraphAnalysticEngine/lib/python3.8/site-packages/graphscope/client/rpc.py", line 101, in run
    return self._run_step_impl(runstep_requests)
  File "/Users/du/.conda/envs/GraphAnalysticEngine/lib/python3.8/site-packages/graphscope/client/utils.py", line 155, in with_grpc_catch
    return fn(*args, **kwargs)
  File "/Users/du/.conda/envs/GraphAnalysticEngine/lib/python3.8/site-packages/graphscope/client/rpc.py", line 193, in _run_step_impl
    raise pickle.loads(response.full_exception)
graphscope.framework.errors.AnalyticalEngineInternalError: /Users/runner/work/GraphScope/GraphScope/analytical_engine/core/utils/lib_utils.h:38: open_lib -> Failed to open library: /tmp/gs/builtin/e1ba0796515bc85372f70618d0a21153e68a0e3f26e9374eebe573551acb16b9/libe1ba0796515bc85372f70618d0a21153e68a0e3f26e9374eebe573551acb16b9.dylib. Reason: dlopen(/tmp/gs/builtin/e1ba0796515bc85372f70618d0a21153e68a0e3f26e9374eebe573551acb16b9/libe1ba0796515bc85372f70618d0a21153e68a0e3f26e9374eebe573551acb16b9.dylib, 0x0001): symbol not found in flat namespace '__ZN8vineyard10ObjectMeta11AddKeyValueERKNSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEERKN8nlohmann12json_v3_11_110basic_jsonINS1_3mapENS1_6vectorES7_bxydS5_NSB_14adl_serializerENSE_IhNS5_IhEEEEEE'
/Users/runner/work/GraphScope/GraphScope/analytical_engine/core/utils/lib_utils.h:38: open_lib -> Failed to open library: /tmp/gs/builtin/e1ba0796515bc85372f70618d0a21153e68a0e3f26e9374eebe573551acb16b9/libe1ba0796515bc85372f70618d0a21153e68a0e3f26e9374eebe573551acb16b9.dylib. Reason: dlopen(/tmp/gs/builtin/e1ba0796515bc85372f70618d0a21153e68a0e3f26e9374eebe573551acb16b9/libe1ba0796515bc85372f70618d0a21153e68a0e3f26e9374eebe573551acb16b9.dylib, 0x0001): symbol not found in flat namespace '__ZN8vineyard10ObjectMeta11AddKeyValueERKNSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEERKN8nlohmann12json_v3_11_110basic_jsonINS1_3mapENS1_6vectorES7_bxydS5_NSB_14adl_serializerENSE_IhNS5_IhEEEEEE'
```

**Expected behavior**
Is it a bug or working as design?

**Screenshots**

**Environment (please complete the following information):**
 - GraphScope version: master (0.16.0a20220922)
 - OS: MacOS, Ubuntu 20.04
 - Version 12.3
 - Kubernetes Version 1.22.4

**Additional context**

**Comment by sighingnow** [comment] 2022-09-27 03:27
@dzhiwei  Do you install graphscope using pip, or build and install from source?

**Comment by dzhiwei** [comment] 2022-09-27 07:54
> @dzhiwei Do you install graphscope using pip, or build and install from source?

I am using pip install, version of graphscope and graphscope-client  is 0.16.0a20220922

**Comment by sighingnow** [comment] 2022-09-28 02:22
Cannot reproduce the same error on both Ubuntu 20.04 (using our docker image `registry.cn-hongkong.aliyuncs.com/graphscope/graphscope:nightly`) and MacOS.

- louvain: cannot reproduce
- wcc: problem in WCC with string OIDs has already been fixed on main
- lpa: problem in LPA (CDLP) with string OIDs will be addressed by https://github.com/alibaba/libgrape-lite/pull/128

**Comment by sighingnow** [comment] 2022-09-28 06:08
Enhancement in https://github.com/alibaba/GraphScope/pull/2089 would be helpful to diagnose the frame/app releated errors, especially build errors and unexpected runtime exceptions.

**Comment by dzhiwei** [comment] 2022-09-28 06:17
louvain works fine with oid_type 'string', it turns out that the version of my local graphscope is too old

**Closed** 2022-09-28 08:18 UTC
Labels: bug, component:gae
