### ISSUE TITLE
[BUG] result protocol not aligned with the standard

### ISSUE THREAD

**Issue by shirly121** [alibaba/GraphScope#284] opened 2021-05-11 06:18 UTC
**Describe the bug**
For some test queries that produce vertices or edges results, gremlin test will check the correctness of these queries by verifying the properties of vertices or edges, thus require the results to carry with the properties info. For message reduction, we just ignore the properties when returning results.

**To Reproduce**
// java sdk
Traversal<Vertex, Vertex> traversal = g.V().repeat(__.out()).times(2);
 int counter = 0;
while(traversal.hasNext()) {
    ++counter;
    Vertex vertex = (Vertex)traversal.next();
    Assert.assertTrue(vertex.value("name").equals("lop") || vertex.value("name").equals("ripple"));
}

**Comment by zhengpingq** [comment] 2021-05-11 09:56
According to https://stackoverflow.com/questions/45764199/janusgraph-cluster-always-returns-vertex-without-properties-referencevertex, this is caused by a similar behavior in JanusGraph for working with remote graphs (which is always the case in GAIA). I'd suggest adding this to the documentation, and then close this issue.

**Closed** 2021-05-14 03:49 UTC
Labels: bug, component:doc, component:gaia, component:gie

**Comment by shirly121** [comment] 2021-05-14 06:37
For each query producing vertex/edge results, Gaia compiler always returns minimal information while gremlin tests need full information including properties, so here is a contradiction. To solve the issue and pass more gremlin tests, compiler maintains properties locally and fills each vertex/edge structure with the local properties after pegasus returning the minimal info.
The link <https://stackoverflow.com/questions/45764199/janusgraph-cluster-always-returns-vertex-without-properties-referencevertex> will be added to documentation later for the consideration of how to place it.
