### ISSUE TITLE
about duplicate vertex and edge

### ISSUE THREAD

**Issue by yecol** [alibaba/GraphScope#1877] opened 2022-07-25 02:16 UTC
### Discussed in https://github.com/alibaba/GraphScope/discussions/1845

<div type='discussions-op-text'>

<sup>Originally posted by **wuyueandrew** July 14, 2022</sup>
consider a bench dataset like：

vertex label a:
```
aid
1
2
3
3
```

vertex label b:
```
bid
6
6
7
```

edge(a -> b)
```
src_id,dst_id
1,6
2,6
3,7
```

```
graph = graph.add_vertices('/tmp/dataset_test/duplicate_dataset/a.csv', label='a', vid_field='aid')
graph = graph.add_vertices('/tmp/dataset_test/duplicate_dataset/b.csv', label='b', vid_field='bid')
graph = graph.add_edges('/tmp/dataset_test/duplicate_dataset/a_to_b.csv',
                        src_label='a',
                        dst_label='b')
interactive = sess.gremlin(graph)

node_num = interactive.execute("g.V().count()").one()
edge_num = interactive.execute("g.E().count()").one()
```

What's the reason of node_num=7, edge_num=3 ?
I think `node_num=7` and `edge_num=3` are confilct.
1.Duplicate vertexs which have equal vid_field can be create repeatly ? 
Is vid_field a unique key and gs has a oid like primary key?
2.If the answer 1 is yes, the edge number should be 5 (2 * (1->6) + 2 * (2->6) + 1 * (3 ->7)) i thought.
what's the reason of edge_num = 3 (due to this, duplicate vertexs which have equal vid_field can not be created obviously)?
</div>

**Comment by acezen** [comment] 2022-07-25 02:22
I think the real reason is GraphScope do not deduplicate the vertices and edges in graph loading processing.

**Comment by wuyueandrew** [comment] 2022-08-03 08:56
这个问题现在有初步的结论么，我比较好奇

**Comment by sighingnow** [comment] 2022-08-03 09:43
It is expected.

Duplicates vertices in the vertex data files will causing duplicated nodes when scan vertices.

The underlying implementation works as the following way:

- When loading graph, vineyard first scanning all vertices, creating an vertice array and a hashmap, where
   - the vertices array is all given vertices (without dedup), in this case, the size would be 7
   - the hashmap contains a mapping between the original vertice id to an internal id, in this case, the size would be 5
 - Then vineyard's graph loader will scan all vertices, and building the CSR, based on the internal id stored in the hashmap, thus the edge is 3 in this case.

The requirements for non-duplicated orginal vertice id in the source data is by design.

Hope the information about could be helpful for your question.

**Comment by sighingnow** [comment] 2022-08-03 09:43
Closing as answered. Feel free to comment or reopen your still has further questions.

**Closed by sighingnow** 2022-08-03 09:43 UTC
Labels: question, component:vineyard
