### ISSUE TITLE
runtime support failover

### ISSUE THREAD

**Issue by tianliplus** [alibaba/GraphScope#1713] opened 2022-06-13 07:42 UTC
We noticed that the quering service is abnormal after pod failure and restart.

- [x] Support failover for executor
- [x] Add CI tests for pegasus failover
- [x] Add CI tests for frontend failover
- [ ] Add CI tests for ingestor failover
- [ ] Add CI tests for coordinator failover

**Comment by tianliplus** [comment] 2022-06-13 07:47
after some store node restart (full restart is OK), new queries cannot completed.

**Comment by siyuan0322** [comment] 2022-07-20 07:55
Kill some worker and let it restart. Some worker will not found its new peer.

2022-07-20 15:26:41.560437789 ERROR (/home/graphscope/gs/research/engine/pegasus/network/src/send/mod.rs:254) [net-sender-2] fail to send data to 2, caused by No route to host (os error 113);

**Comment by siyuan0322** [comment] 2023-04-13 02:20
Resolved by add dns refreshing in grpc connections.

**Closed by siyuan0322** 2023-04-13 02:20 UTC
Labels: bug
