### ISSUE TITLE
训练时目前只用到一个cpu核？不能配置多核训练？

### ISSUE THREAD

**Issue by bookug** [alibaba/GraphScope#1437] opened 2022-03-31 11:40 UTC
在训练时发现cpu占有率只有130%，目前是不支持多核训练么？

**Comment by sighingnow** [comment] 2022-04-08 13:37
@xiaoming-qxm @baoleai,

Could you folks take a look at this issue and if possible, give some guidence to users?

Thanks!

**Comment by baoleai** [comment] 2022-04-11 02:32
This issue is a duplicate of the one in Graph-Learn https://github.com/alibaba/graph-learn/issues/185

**Comment by sighingnow** [comment] 2022-04-11 03:41
Thanks @baoleai ❤️ 

Close as answered in https://github.com/alibaba/graph-learn/issues/185

**Closed by sighingnow** 2022-04-11 03:41 UTC
Labels: component:gle, component:python
