### ISSUE TITLE
[BUG] can't pull images from registry.cn-hongkong.aliyuncs.com

### ISSUE THREAD

**Issue by zhangzhuoBYS** [alibaba/GraphScope#2483] opened 2023-03-06 01:42 UTC
**Describe the bug**
can't pull images from registry.cn-hongkong.aliyuncs.com！
when use helm to install the cluster flollowing by the Official manual
, `ImagePullBackOff` raised.
![图片](https://user-images.githubusercontent.com/40155703/223000973-db47b3f5-0e07-4e87-9263-2eff065aefc8.png)

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - GraphScope version: [e.g., v0.1, v0.2.2, master]
 - OS: [e.g. MacOS, Linux]
 - Version [e.g. 10.15]
 - Kubernetes Version [e.g., 1.19]

**Additional context**

**Comment by sighingnow** [comment] 2023-03-06 02:23
From the error message you can see that containerd was complaining that the disk is full is no space left, thus failed to pull the docker image.

It is not a bug of graphscope. You could try to cleanup your disk to reserve spaces for images and try gain.

**Comment by sighingnow** [comment] 2023-03-06 02:23
Closing as moving to discussion.

**Closed by sighingnow** 2023-03-06 02:23 UTC
