### ISSUE TITLE
[BUG] query vertex's neighbors occurs bug occasionally

### ISSUE THREAD

**Issue by BingqingLyu** [alibaba/GraphScope#2125] opened 2022-10-11 02:43 UTC
**Describe the bug**

An example is `g.V().has("symbol", "symbol_id", xx).in("road_symbol").out("road_symbol").values("type")`, which outputs unexpected results. 
This bug seems related to vertex shuffling, as it outputs the following error info occasionally:

> 2022-10-10 17:34:36.254279560 ERROR (/work/interactive_engine/executor/engine/pegasus/server/src/rpc.rs:180) [tokio-runtime-worker] submit job 126 failure: Build(user defined error: Not supported: get server id failed in graph_partition_manager in source op QueryStoreError("get server index by given partition id failed in Vineyard"))

**Comment by sighingnow** [comment] 2022-10-12 05:34
Closed as caused by the non-terminated java process and the issue has already been resolved in user's environment.

**Closed by sighingnow** 2022-10-12 05:34 UTC
Labels: bug, component:gie
