### ISSUE TITLE
[BUG] The analytical engine server may down

### ISSUE THREAD

**Issue by zpf4934** [alibaba/GraphScope#1142] opened 2021-12-09 10:43 UTC
**Environment (please complete the following information):**
 - GraphScope version: [0.9.0]
 - OS: [docker Linux]
 - Version python3.7

**Additional context**

```
*** Aborted at 1639045818 (unix time) try "date -d @1639045818" if you are using GNU date ***
PC: @                0x0 (unknown)
*** SIGBUS (@0x7f05fc0be000) received by PID 6011 (TID 0x7f070e7fc700) from PID 18446744073643220992; stack trace: ***
    @     0x7f076a542140 (unknown)
    @     0x7f0769673dd3 (unknown)
    @     0x7f0764207d80 vineyard::FixedSizeBinaryArrayBuilder::Build()
    @     0x7f076426a244 vineyard::FixedSizeBinaryArrayBaseBuilder::_Seal()
    @     0x7f076a60cbfb vineyard::ObjectBuilder::Seal()
    @     0x7f0764284940 _ZZN8vineyard13ArrowFragmentIlmE16AddNewEdgeLabelsERNS_6ClientEOSt6vectorISt10shared_ptrIN5arrow5TableEESaIS8_EERKS4_ISt3setISt4pairISsSsESt4lessISE_ESaISE_EESaISI_EEiENKUlS3_E2_clES3_
    @     0x7f076432b6c4 _ZZN8vineyard11ThreadGroup7AddTaskIRZNS_13ArrowFragmentIlmE16AddNewEdgeLabelsERNS_6ClientEOSt6vectorISt10shared_ptrIN5arrow5TableEESaISA_EERKS6_ISt3setISt4pairISsSsESt4lessISG_ESaISG_EESaISK_EEiEUlS5_E2_JSt17reference_wrapperIS4_EEEEjOT_DpOT0_ENKUljSQ_DpOT_E_clIJS5_EEENS_6StatusEjSQ_S10_
    @     0x7f076432ba47 _ZNSt17_Function_handlerIFSt10unique_ptrINSt13__future_base12_Result_baseENS2_8_DeleterEEvENS1_12_Task_setterIS0_INS1_7_ResultIN8vineyard6StatusEEES3_EZNS1_11_Task_stateISt5_BindIFZNS8_11ThreadGroup7AddTaskIRZNS8_13ArrowFragmentIlmE16AddNewEdgeLabelsERNS8_6ClientEOSt6vectorISt10shared_ptrIN5arrow5TableEESaISO_EERKSK_ISt3setISt4pairISsSsESt4lessISU_ESaISU_EESaISY_EEiEUlSJ_E2_JSt17reference_wrapperISI_EEEEjOT_DpOT0_EUljS14_DpOT_E_jS13_S16_EESaIiEFS9_vEE6_M_runEvEUlvE_S9_EEE9_M_invokeERKSt9_Any_data
    @     0x7f0773cfa51d std::function<>::operator()()
    @     0x7f0773cf21af std::__future_base::_State_baseV2::_M_do_set()
    @     0x7f0773cfdfb5 std::__invoke_impl<>()
    @     0x7f0773cfbb65 std::__invoke<>()
    @     0x7f0773cfa26a _ZZSt9call_onceIMNSt13__future_base13_State_baseV2EFvPSt8functionIFSt10unique_ptrINS0_12_Result_baseENS4_8_DeleterEEvEEPbEJPS1_S9_SA_EEvRSt9once_flagOT_DpOT0_ENKUlvE_clEv
    @     0x7f0773cfa29d _ZZSt9call_onceIMNSt13__future_base13_State_baseV2EFvPSt8functionIFSt10unique_ptrINS0_12_Result_baseENS4_8_DeleterEEvEEPbEJPS1_S9_SA_EEvRSt9once_flagOT_DpOT0_ENKUlvE0_clEv
    @     0x7f0773cfa2ae _ZZSt9call_onceIMNSt13__future_base13_State_baseV2EFvPSt8functionIFSt10unique_ptrINS0_12_Result_baseENS4_8_DeleterEEvEEPbEJPS1_S9_SA_EEvRSt9once_flagOT_DpOT0_ENUlvE0_4_FUNEv
    @     0x7f076a53f34f __pthread_once_slow
    @     0x7f07641d8c82 _ZNSt13__future_base11_Task_stateISt5_BindIFZN8vineyard11ThreadGroup7AddTaskIRZNS2_13ArrowFragmentIlmE16AddNewEdgeLabelsERNS2_6ClientEOSt6vectorISt10shared_ptrIN5arrow5TableEESaISD_EERKS9_ISt3setISt4pairISsSsESt4lessISJ_ESaISJ_EESaISN_EEiEUlS8_E2_JSt17reference_wrapperIS7_EEEEjOT_DpOT0_EUljST_DpOT_E_jSS_SV_EESaIiEFNS2_6StatusEvEE6_M_runEv
    @     0x7f0773ea88d0 execute_native_thread_routine
    @     0x7f076a536ea7 start_thread
    @     0x7f076960edef clone
    @                0x0 (unknown)
2021-12-09 10:30:19,907 [ERROR][rpc:54]: rpc _run_step_impl: failed with error code StatusCode.UNAVAILABLE, details: Connection reset by peer
2021-12-09 10:30:19,906 [ERROR][coordinator:351]: Engine RunStep failed, code: UNAVAILABLE, details: Connection reset by peer
2021-12-09 10:30:19,907 [WARNING][coordinator:297]: Connect to analytical engine failed, engine may not started or closed. code: UNAVAILABLE, details: Connection reset by peer
2021-12-09 10:30:24,911 [WARNING][coordinator:297]: Connect to analytical engine failed, engine may not started or closed. code: UNAVAILABLE, details: failed to connect to all addresses
2021-12-09 10:30:29,914 [ERROR][coordinator:1022]: Cleanup failed, code: UNAVAILABLE, details: failed to connect to all addresses
2021-12-09 10:30:30,072 [ERROR][coordinator:1022]: Cleanup failed, code: UNAVAILABLE, details: failed to connect to all addresses
---------------------------------------------------------------------------
FatalError                                Traceback (most recent call last)
/tmp/ipykernel_5893/2959305589.py in <module>
      3 from graphscope.dataset import load_ogbn_mag
      4 
----> 5 graph = load_ogbn_mag()

~/miniconda3/lib/python3.8/site-packages/graphscope/dataset/ogbn_mag.py in load_ogbn_mag(sess, prefix)
     77     graph = sess.g()
     78     graph = (
---> 79         graph.add_vertices(os.path.join(prefix, "paper.csv"), "paper")
     80         .add_vertices(os.path.join(prefix, "author.csv"), "author")
     81         .add_vertices(os.path.join(prefix, "institution.csv"), "institution")

~/miniconda3/lib/python3.8/site-packages/graphscope/framework/graph.py in add_edges(self, edges, label, properties, src_label, dst_label, src_field, dst_field)
   1084         if not self.loaded():
   1085             raise RuntimeError("The graph is not loaded")
-> 1086         return self._session._wrapper(
   1087             self._graph_node.add_edges(
   1088                 edges, label, properties, src_label, dst_label, src_field, dst_field

~/miniconda3/lib/python3.8/site-packages/graphscope/client/session.py in _wrapper(self, dag_node)
    923     def _wrapper(self, dag_node):
    924         if self.eager():
--> 925             return self.run(dag_node)
    926         else:
    927             return dag_node

~/miniconda3/lib/python3.8/site-packages/graphscope/client/session.py in run(self, fetches, debug)
    952         fetch_handler = _FetchHandler(self.dag, fetches)
    953         try:
--> 954             response = self._grpc_client.run(fetch_handler.targets)
    955         except FatalError:
    956             self.close()

~/miniconda3/lib/python3.8/site-packages/graphscope/client/rpc.py in run(self, dag_def)
    143 
    144     def run(self, dag_def):
--> 145         return self._run_step_impl(dag_def)
    146 
    147     def fetch_logs(self):

~/miniconda3/lib/python3.8/site-packages/graphscope/client/rpc.py in with_grpc_catch(*args, **kwargs)
     56                     % (fn.__name__, exc.code(), exc.details())
     57                 )
---> 58                 raise FatalError("The analytical engine server may down.") from None
     59             else:
     60                 raise GRPCError(

FatalError: 'The analytical engine server may down.'
```

**Comment by siyuan0322** [comment] 2021-12-09 13:14
Seems caused by not enough memory. Are you running this script in a docker container?
If so, try using the flag `shm-size`, used like this `docker run --shm-size=4096m'.

**Comment by siyuan0322** [comment] 2021-12-31 02:25
Closed as staleness.

**Closed by siyuan0322** 2021-12-31 02:25 UTC
Labels: enhancement, component:gae
