### ISSUE TITLE
[BUG] Run GraphScope like NetworkX Failed

### ISSUE THREAD

**Issue by JackyYangPassion** [alibaba/GraphScope#2594] opened 2023-04-11 09:42 UTC
**Describe the bug**
Run GraphScope like NetworkX Failed

**To Reproduce**
```
import graphscope
graphscope.set_option(show_log=True)
import graphscope.nx as nx

# Initialize an empty graph
G = nx.Graph()
```
Log

```
ModuleNotFoundError: No module named 'networkx.testing'
```
![image](https://user-images.githubusercontent.com/13795366/231121039-cff026f7-13f7-4567-8cd6-6a72488a66d0.png)

**Environment (please complete the following information):**
 - GraphScope version: V0.20.0
 - OS: Linux

**Comment by acezen** [comment] 2023-04-11 09:44
hi， @JackyYangPassion， can you give your networkx version?

**Comment by JackyYangPassion** [comment] 2023-04-11 10:07
3.1

**Comment by acezen** [comment] 2023-04-11 11:29
> 3.1

Seems that networkx 3.1 has removed the `testing` module, GraphScope has not adapted to the networkx 3.1. We would open a pull request to address the issue. 
BTW, You can run with network 2.8 at first to work around this issue.

**Comment by acezen** [comment] 2023-04-12 01:26
> 3.1

GraphScope python client require networkx 2.8 or 2.6
https://github.com/alibaba/GraphScope/blob/b8232ab328855e491cdd4d5f225c266e61c35e83/python/requirements.txt#L10-L11

**Comment by acezen** [comment] 2023-04-14 03:06
close this issue since GraphScope need NetworkX 2.8 or NetworkX 2.6

**Comment by siyuan0322** [comment] 2023-04-14 03:08
> close this issue since GraphScope need NetworkX 2.8 or NetworkX 2.6

It's not using graphscope.nx but rather the result of graphscope.lpa seems incorrect, waiting to be confirmed or fixed.

**Closed** 2023-04-14 03:08 UTC
